import type { Metadata } from "next";
import { QuickstartProvider } from "@/context/context";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QuickstartProvider>{children}</QuickstartProvider>
      </body>
    </html>
  );
}
